# Generated by Django 5.0.2 on 2024-02-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
