# Generated by Django 5.0.2 on 2024-03-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_aboutmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
