# Generated by Django 5.0.2 on 2024-03-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_aboutmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='image',
            field=models.ImageField(upload_to='images/about'),
        ),
    ]
